version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.5
    working_directory: ~/backRakuten
    # executor: ruby/default
    steps:
      - checkout:
          path: ~/backRakuten
      # - run:
      #     name: Which bundler?
      #     command: bundle -v
      # - ruby/bundle-install
      - ruby/install-deps
  test:
    docker:
      - image: circleci/ruby:2.6.5
      - image: circleci/mysql:5.7.25
        environment:
          MYSQL_DATABASE: backRakuten_test
          MYSQL_USER: root
          MYSQL_ROOT_PASSWORD:
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      APP_DATABASE_HOST: 127.0.0.1
      RAILS_ENV: test
    working_directory: ~/backRakuten
    steps:
      - checkout:
          path: ~/backRakuten
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      # - run:
      # name: test rspec
      - ruby/rspec-test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
